name: Build JupyterLite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
  workflow_call:

jobs:
  build-jupyterlite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install mamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: jupyterlite_build_environment.yml
          cache-environment: true

      - name: Build the JupyterLite site
        shell: bash -l {0}
        run: |
          jupyter lite build --contents notebooks --output-dir dist

      - name: Upload JupyterLite artifact
        uses: actions/upload-artifact@v4
        with:
          name: jupyterlite-site
          path: ./dist
          retention-days: 30
