name: Build Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash -e -l {0}

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set conda environment
        uses: mamba-org/setup-micromamba@main
        with:
          environment-name: myenv
          environment-file: environment-dev.yml
          init-shell: bash
          cache-downloads: true

      - name: Configure using CMake
        run: cmake -G Ninja -Bbuild -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_DOCS=ON

      - name: Build docs target
        run: cmake --build build --target docs

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: build/docs/html
          retention-days: 30
